### ISSUE TITLE
Unable to find module with ID: aurelia-validation

### ISSUE THREAD

**Issue by techmind-git** [michaelbull/aurelia-typescript-webpack-starter#3]
When I add aurelia validation to package.json (as dependency) and in main.ts as follow:

```
export function configure(aurelia: Aurelia): void {
    aurelia.use.standardConfiguration()
    .plugin('aurelia-validation')
    ;
    aurelia.start().then(() => aurelia.setRoot('app'));
}
```

Then i get the error:

```
Uncaught (in promise) Error: Unable to find module with ID: aurelia-validation
    at WebpackLoader.<anonymous> (app.js:16606)
    at step (app.js:16444)
    at Object.next (app.js:16425)
    at app.js:16419
    at 67.__awaiter (app.js:16415)
    at WebpackLoader.67.WebpackLoader._import (app.js:16562)
    at WebpackLoader.<anonymous> (app.js:16671)
    at step (app.js:16444)
    at Object.next (app.js:16425)
    at app.js:16419
```

Any idea what could solve this error?

**Comment by michaelbull** [comment]
@niieani's [answer on the skeleton webpack project](https://github.com/aurelia/webpack-plugin/issues/78#issuecomment-254277899) seems to suggest [declaring your build resources](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/bundling-webpack/6) in the `package.json` file.

Please let me know if the above answer works, thanks.

For what it's worth, I've [had problems](https://github.com/aurelia/webpack-plugin/issues/59#issuecomment-235256233) with the current version of the webpack plugin regarding the use of Aurelia plugins from scoped packages. The solution from the developers seems to be to wait for the new plugins to be released.

I have an [open task](https://github.com/michaelbull/aurelia-typescript-webpack-starter/issues/1) to update this starter kit to use the new webpack plugins as soon as they are released by the team. The [experimental branch](https://github.com/michaelbull/aurelia-typescript-webpack-starter/tree/experimental) is where I'm doing those changes, and it will be merged into master when they have finished releasing the plugins.

**Comment by techmind-git** [comment]
I've added the following to the package.json:
```
"aurelia": {
    "build": {
      "resources": [
        "aurelia-validation"
      ],
      "includeDependencies": "aurelia-*"
    }
  },
```

and tried different combinations of above (ie. only resources, only inlcudeDependencies, both). But the problem remains unfortunately.
Adding the aurelia-validation to the skeleton-navigation webpack/typescript version that uses the easywebpack setup works fine but i don't won't to use easywebpack. 

Have you tried adding validation-plugin somewhere with basis webpack setup?

**Comment by michaelbull** [comment]
Added a working example under the branch [#3-plugin-example](https://github.com/michaelbull/aurelia-typescript-webpack-starter/tree/%233-plugin-example). Interestingly I didn't need to register it in `package.json` at all - it just worked.

Let me know if you're still hitting problems.

**Comment by techmind-git** [comment]
The provided example works. Really appreciate it. 

Tried the experimental branch another time too with cleaned up node_modules (since i had an issue with that getting your example branch working). But the experimental branch is still generating the missing moduleId error when adding the validation plugin.

But I'll use the setup from the example branch until the aurelia team has the official version out.

Many thanks!

**Comment by stefan505** [comment]
The example from @michaelbull doesn't play well with plugins:

```
Uncaught (in promise) Error: Unable to find module with ID: aurelia-validation
```

Anyone any ideas?
